[project]
name = "cvp-reproduction"
version = "0.1.0"
description = ""
authors = [{ name = "Kikis", email = "kikispcmr@gmail.com" }, { name = "vic", email = "victoria_polaka@proton.me"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy (>=2.4.6,<3.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
